### ISSUE TITLE
Manual installation instructions unclear

### ISSUE THREAD

**Issue by LouPit929** [internetarchive/internetarchivebot#11]
I've been following the manual installation instructions to install IABot on a MediaWiki MAMP stack. I am unsure what Step 13 is referring to in terms of completing bot setup through a webbrowser, could you please clarify?

**Comment by weblars** [comment]
I think it may the same as step 7 in the first section:

- Goto http://localhost:8080/ to complete bot setup.

**Comment by Nintendofan885** [comment]
@LouPit929 Hi, issues should be posted on Phabricator instead. I've moved this to https://phabricator.wikimedia.org/T279765
