### ISSUE TITLE
Add single and multiple page run bot buttons on main page of https://iabot.toolforge.org/

### ISSUE THREAD

**Issue by jorlowitz** [internetarchive/internetarchivebot#17]
Improve UX by putting the main bot use triggers front and center, with a short description of which one to use when.

**Comment by decodedfile** [comment]
Duplicate of #

**Comment by Nintendofan885** [comment]
@jorlowitz  Hi, issues should be posted on Phabricator instead. I've moved this to https://phabricator.wikimedia.org/T279766
