### ISSUE TITLE
Adding support for enwn

### ISSUE THREAD

**Issue by acagastya** [internetarchive/internetarchivebot#9]
Hello, @cyberpower678.  I am [[[user:acagastya]]](https://en.wikinews.org/wiki/User:Acagastya), a sysop on enwn and I wondered if it would it be possible to add the feature to archive the sources used on enwikinews?

There might be < 22k articles in the [[[Category:Published]]](https://en.wikinews.org/wiki/Category:Published) -- all of whose sources needs to be archived.  If the bot also archives the enternal links, that is greatly appreciated.

Please note, the bot does NOT have to edit the articles, just extract the URLs and archive them, if the link exists on the internet.

After all the sources are archived, could you then set the bot to archive any new mainspace articles that are added to the published category?

This would be greatly appreciated feature.

**Comment by Nintendofan885** [comment]
@acagastya Hi, issues should be posted on Phabricator instead. I've moved this to https://phabricator.wikimedia.org/T267331
